// frontend_angular/src/app/pages/mylistings/mylistings.component.ts
import { Component, OnInit } from '@angular/core';
import { ListingService } from '../listing.services';
import { Book } from '../book.model';
import { AddBookComponent } from '../add-book/add-book.component'; // Import AddBookComponent

@Component({
  selector: 'app-mylistings',
  templateUrl: './mylistings.component.html',
  styleUrls: ['./mylistings.component.css']
})
export class MylistingsComponent implements OnInit {
  listings: Book[] = [];
  selectedBook: Book | null = null;
  showDeleteConfirmation: boolean = false;
  showUpdateConfirmation: boolean = false;
  showAddBook: boolean = false;

  constructor(private listingService: ListingService) { }

  ngOnInit(): void {
    this.fetchUserListings();
  }

  fetchUserListings() {
    const token = localStorage.getItem('authToken');
    if (token) {
      this.listingService.getUserListings(token).subscribe(listings => {
        this.listings = listings;
      });
    } else {
      console.error('Authentication token is missing. Please log in.');
    }
  }

  handleUpdateListing(book: Book) {
    // If the same book is clicked again, close the form
    if (this.selectedBook === book) {
      this.selectedBook = null;
      this.showAddBook = false; // Close the form
    } else {
      // Otherwise, open the update form for the selected book
      this.selectedBook = book;
      this.openUpdateBookForm(book);
    }
  }
  

  handleDeleteListing(isbn: string) {
    const token = localStorage.getItem('authToken');
    if (token) {
      this.listingService.deleteUserListing(isbn, token).subscribe(() => {
        this.listings = this.listings.filter(listing => listing.ISBN !== isbn);
        this.showDeleteConfirmation = true;
      }, error => {
        console.error('Error deleting listing:', error);
      });
    }
  }

  handleCloseForm() {
    this.selectedBook = null;
    this.fetchUserListings();
    if (this.showAddBook) {
      this.showUpdateConfirmation = true; 
    }
  }
  
  toggleAddBookForm() {
    this.showAddBook = !this.showAddBook;
  }

  openAddBookForm() {
    this.selectedBook = null;
    this.showAddBook = true;
  }

  openUpdateBookForm(book: Book) {
    this.selectedBook = book;
    this.showAddBook = true;
  }
}

<div class="container">
    <button class="btn btn-success" style="margin-top: 20px;" (click)="toggleAddBookForm()">Add Book</button>
    <br /><br />
  
    <div *ngIf="listings.length > 0; else noListings">
      <div *ngFor="let listing of listings" style="margin-bottom: 10px; padding: 10px; border: 1px solid #ccc; border-radius: 8px; display: flex; align-items: center;">
        <!-- Display listing details -->
        <img [src]="listing.img" [alt]="listing.title" style="height: 80px; margin-right: 10px;" />
        <div>
          <p>Title: {{ listing.title }}</p>
          <p>Author: {{ listing.author }}</p>
        </div>
        <div style="margin-left: auto;">
          <button class="btn btn-primary" (click)="handleUpdateListing(listing)">Update</button>
          <button class="btn btn-danger" (click)="handleDeleteListing(listing.ISBN)">Delete</button>
        </div>
      </div>
    </div>
    <ng-template #noListings>
      <p>No listings found</p>
    </ng-template>
    <div *ngIf="showDeleteConfirmation" class="alert alert-success" role="alert">
      Listing deleted successfully!
    </div>
    <div *ngIf="showUpdateConfirmation" class="alert alert-success" role="alert">
      Listing updated successfully!
    </div>
  </div>

  <div *ngIf="showAddBook">
    <app-add-book 
      *ngIf="!selectedBook; else updateBookForm"
    ></app-add-book>
    <ng-template #updateBookForm>
      <app-add-book [bookObj]="selectedBook" [isUpdateMode]="true" *ngIf="selectedBook"></app-add-book>
    </ng-template>
  </div>

// frontend/pages/mylistings.tsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import Layout from '../components/Layout';
import UpdateBook from '../components/UpdateBook';
import AddBook from '../components/addbook';
import { Button } from 'react-bootstrap';
import { useRouter } from 'next/router';

interface Listing {
  ISBN: string;
  img: string;
  title: string;
  author: string;
  inventory: number;
  category: string;
  isExchange: boolean;
}

const apiUrl = process.env.NEXT_PUBLIC_API_URL;

const MyListings: React.FC = () => {
  const [listings, setListings] = useState<Listing[]>([]);
  const [selectedBook, setSelectedBook] = useState<Listing | null>(null);
  const [showDeleteConfirmation, setShowDeleteConfirmation] = useState<boolean>(false);
  const [showUpdateConfirmation, setShowUpdateConfirmation] = useState<boolean>(false);
  const [showAddBook, setShowAddBook] = useState<boolean>(false);
  const router = useRouter();

  useEffect(() => {
    fetchUserListings();
  }, []);

  const fetchUserListings = async () => {
    try {
      const token = localStorage.getItem('token');
      if (!token) {
        router.push('/login');
        return;
      }
      const response = await axios.get<Listing[]>(`${apiUrl}/api/user-listings`, {
        headers: { Authorization: token }
      });
      setListings(response.data);
    } catch (error) {
      console.error('Error fetching user listings:', error);
    }
  };

  const handleUpdateListing = (book: Listing) => {
    setSelectedBook(book);
  };

  const handleDeleteListing = async (isbn: string) => {
    try {
      const token = localStorage.getItem('token');
      await axios.delete(`${apiUrl}/api/delete-user-listing/${isbn}`, {
        headers: { Authorization: token }
      });
      setListings(prevListings => prevListings.filter(listing => listing.ISBN !== isbn));
      setShowDeleteConfirmation(true);
    } catch (error) {
      console.error('Error deleting listing:', error);
    }
  };

  const handleCloseForm = () => {
    setSelectedBook(null);
    fetchUserListings();
    setShowUpdateConfirmation(true);
  };

  return (
    <Layout>
      <div className='container'>
      <h1 style={{ fontWeight: 'bold', marginBottom: '16px', textAlign: 'center' }}>My Listings</h1>
        <Button variant="success" onClick={() => setShowAddBook(true)}>Add Book</Button>{' '}
        <br /><br />
        {showAddBook && <AddBook onClose={() => setShowAddBook(false)} />} {/* Close the AddBook form */}
        {listings.map(listing => (
          <div key={listing.ISBN} style={{ marginBottom: '10px', padding: '10px', border: '1px solid #ccc', borderRadius: '8px', display: 'flex', alignItems: 'center' }}>
            <img src={listing.img} alt={listing.title} style={{ height: '80px', marginRight: '10px' }} />
            <div>
              <p>Title: {listing.title}</p>
              <p>Author: {listing.author}</p>
            </div>
            <div style={{ marginLeft: 'auto' }}>
              <Button variant="primary" onClick={() => handleUpdateListing(listing)}>Update</Button>{' '}
              <Button variant="danger" onClick={() => handleDeleteListing(listing.ISBN)}>Delete</Button>
            </div>
          </div>
        ))}
        {selectedBook && (
          <div style={{ marginTop: '20px' }}>
            <h2>Update Listing</h2>
            <UpdateBook initialValues={selectedBook} onSubmit={handleCloseForm} onClose={handleCloseForm} />
          </div>
        )}
        {showDeleteConfirmation && (
          <div className="alert alert-success" role="alert">
            Listing deleted successfully!
          </div>
        )}
        {showUpdateConfirmation && (
          <div className="alert alert-success" role="alert">
            Listing updated successfully!
          </div>
        )}
      </div>
    </Layout>
  );
};

export default MyListings;
