// frontend/src/app/listings/page.tsx
"use client";
import React, { useState, useEffect } from "react";
import { FaShoppingCart, FaExchangeAlt } from "react-icons/fa";
import Layout from "../components/Layout";
import BookCard from "@/src/app/components/BookCard";

interface Listing {
  ISBN: string;
  img: string;
  title: string;
  author: string;
  inventory: number;
  category: string;
  isExchange: boolean;
}

const listingsPerPage = 18;

const Listings = () => {
  const [listings, setListings] = useState<Listing[]>([]);
  const [currentPage, setCurrentPage] = useState(1);
  const [searchTerm, setSearchTerm] = useState("");
  const [filterExchange, setFilterExchange] = useState(false);
  const [showRequestPopup, setShowRequestPopup] = useState(false);
  const [selectedListingUser, setSelectedListingUser] = useState(null);
  const [showAddToCartPopup, setShowAddToCartPopup] = useState(false);
  const [selectedBookId, setSelectedBookId] = useState(null);

  useEffect(() => {
    const fetchListings = async () => {
      try {
        const response = await fetch("/api/listings/index");
        const data = await response.json();
        setListings(data);
      } catch (error) {
        console.error("Error fetching listings:", error);
      }
    };

    fetchListings();
  }, []);

  const filteredListings = listings.filter((listing) => {
    if (filterExchange && !listing.isExchange) return false;
    if (searchTerm === "") return true;
    return listing.title.toLowerCase().includes(searchTerm.toLowerCase());
  });

  const indexOfLastListing = currentPage * listingsPerPage;
  const indexOfFirstListing = indexOfLastListing - listingsPerPage;
  const currentListings = filteredListings.slice(
    indexOfFirstListing,
    indexOfLastListing
  );

  const nextPage = () => setCurrentPage(currentPage + 1);
  const prevPage = () => setCurrentPage(currentPage - 1);

  const fetchUserDetails = async (userId) => {
    try {
      const response = await fetch(`/api/user/${userId}`); // Use backticks for template string
      const data = await response.json();
      setSelectedListingUser(data);
    } catch (error) {
      console.error("Error fetching user details:", error);
    }
  };

  const handleExchangeClick = async (userId, bookId) => {
    try {
      await fetchUserDetails(userId);
      setShowRequestPopup(true);
      setSelectedBookId(bookId); // Set selected bookId
      console.log(bookId);
    } catch (error) {
      console.error("Error handling exchange click:", error);
    }
  };

  const handleRequestClick = async () => {
    try {
      const token = localStorage.getItem("token");
      if (!token) {
        return;
      }

      await fetch("/api/exchange/send", {
        method: "POST",
        headers: {
          Authorization: token,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          receiverEmail: selectedListingUser.email,
          receiverId: selectedListingUser._id,
          bookId: selectedBookId,
        }),
      });

      console.log(selectedBookId);
      setShowRequestPopup(false);
    } catch (error) {
      console.error("Error sending exchange request:", error);
    }
  };

  const handleAddToCartClick = (userId) => {
    fetchUserDetails(userId);
    setShowAddToCartPopup(true);
  };

  return (
    <Layout>
      <div style={{ display: "grid", gridTemplateColumns: "1fr", gap: "16px" }}>
        <div>
          <div
            style={{
              background: "white",
              padding: "16px",
              borderRadius: "4px",
              boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
            }}
          >
            <h3
              style={{
                fontSize: "20px",
                fontWeight: "bold",
                marginBottom: "16px",
                textAlign: "center",
              }}
            >
              Listings
            </h3>
            <input
              type="text"
              placeholder="Search by book name"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              style={{ marginBottom: "16px", padding: "8px", width: "100%" }}
            />
            <label>
              <input
                type="checkbox"
                checked={filterExchange}
                onChange={() => setFilterExchange(!filterExchange)}
              />
              Show Exchange Listings
            </label>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
                gap: "16px",
              }}
            >
              {currentListings.map((listing, index) => (
                <div
                  key={index}
                  style={{
                    position: "relative",
                    background: "#f4f4f4",
                    padding: "16px",
                    borderRadius: "4px",
                    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
                    overflow: "hidden",
                  }}
                >
                  <BookCard item={listing} />
                  {listing.isExchange ? (
                    <button
                      onClick={() =>
                        handleExchangeClick(listing.userId, listing._id)
                      } // Pass bookId to handleExchangeClick
                      style={{
                        position: "absolute",
                        bottom: "8px",
                        right: "8px",
                        background: "none",
                        border: "1px solid #3182ce",
                        borderRadius: "50%",
                        padding: "10px",
                        cursor: "pointer",
                      }}
                      aria-label="Send Exchange Request"
                    >
                      <div
                        style={{
                          background: "white",
                          borderRadius: "50%",
                          padding: "4px",
                        }}
                      >
                        <FaExchangeAlt
                          style={{ fontSize: "1.2rem", color: "#3182ce" }}
                        />
                      </div>
                    </button>
                  ) : (
                    <button
                      onClick={() => handleAddToCartClick(listing.userId)}
                      style={{
                        position: "absolute",
                        bottom: "8px",
                        right: "8px",
                        background: "none",
                        border: "1px solid #3182ce",
                        borderRadius: "50%",
                        padding: "10px",
                        cursor: "pointer",
                      }}
                      aria-label="Add to Cart"
                    >
                      <div
                        style={{
                          background: "white",
                          borderRadius: "50%",
                          padding: "4px",
                        }}
                      >
                        <FaShoppingCart
                          style={{ fontSize: "1.2rem", color: "#3182ce" }}
                        />
                      </div>
                    </button>
                  )}
                </div>
              ))}
            </div>
            <div
              style={{
                display: "flex",
                justifyContent: "center",
                marginTop: "16px",
              }}
            >
              <button
                onClick={prevPage}
                disabled={currentPage === 1}
                style={{
                  background: "#3182ce",
                  color: "white",
                  padding: "8px 12px",
                  border: "none",
                  borderRadius: "4px",
                  margin: "0 4px",
                  cursor: "pointer",
                }}
              >
                Previous
              </button>
              <button
                onClick={nextPage}
                disabled={currentListings.length < listingsPerPage}
                style={{
                  background: "#3182ce",
                  color: "white",
                  padding: "8px 12px",
                  border: "none",
                  borderRadius: "4px",
                  margin: "0 4px",
                  cursor: "pointer",
                }}
              >
                Next
              </button>
            </div>
          </div>
        </div>
      </div>
      {showRequestPopup && selectedListingUser && (
        <div
          style={{
            position: "fixed",
            top: "0",
            left: "0",
            right: "0",
            bottom: "0",
            background: "rgba(0, 0, 0, 0.5)",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            zIndex: "9999",
          }}
        >
          <div
            style={{
              background: "white",
              padding: "24px",
              borderRadius: "8px",
              boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
              maxWidth: "400px",
              width: "90%",
            }}
          >
            <p
              style={{
                fontSize: "18px",
                marginBottom: "16px",
                textAlign: "center",
              }}
            >
              Send book exchange request to <b>{selectedListingUser.email}</b>
            </p>
            <div
              style={{
                display: "flex",
                justifyContent: "center",
                marginTop: "24px",
              }}
            >
              <button
                onClick={() => setShowRequestPopup(false)}
                style={{
                  background: "#ccc",
                  color: "black",
                  padding: "10px 20px",
                  border: "none",
                  borderRadius: "4px",
                  cursor: "pointer",
                  marginRight: "12px",
                  fontWeight: "bold",
                }}
              >
                Cancel
              </button>
              <button
                onClick={handleRequestClick}
                style={{
                  background: "#3182ce",
                  color: "white",
                  padding: "10px 20px",
                  border: "none",
                  borderRadius: "4px",
                  cursor: "pointer",
                  fontWeight: "bold",
                }}
              >
                Send Request
              </button>
            </div>
          </div>
        </div>
      )}
      {showAddToCartPopup && selectedListingUser && (
        <div
          style={{
            position: "fixed",
            top: "0",
            left: "0",
            right: "0",
            bottom: "0",
            background: "rgba(0, 0, 0, 0.5)",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            zIndex: "9999",
          }}
        >
          <div
            style={{
              background: "white",
              padding: "24px",
              borderRadius: "8px",
              boxShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
              maxWidth: "400px",
              width: "90%",
            }}
          >
            <p
              style={{
                fontSize: "18px",
                marginBottom: "16px",
                textAlign: "center",
              }}
            >
              Add book to cart
            </p>
            <div
              style={{
                display: "flex",
                justifyContent: "center",
                marginTop: "24px",
              }}
            >
              <button
                onClick={() => setShowAddToCartPopup(false)}
                style={{
                  background: "#ccc",
                  color: "black",
                  padding: "10px 20px",
                  border: "none",
                  borderRadius: "4px",
                  cursor: "pointer",
                  marginRight: "12px",
                  fontWeight: "bold",
                }}
              >
                Cancel
              </button>
              <button
                onClick={() => console.log("Added to Cart")}
                style={{
                  background: "#3182ce",
                  color: "white",
                  padding: "10px 20px",
                  border: "none",
                  borderRadius: "4px",
                  cursor: "pointer",
                  fontWeight: "bold",
                }}
              >
                Add to Cart
              </button>
            </div>
          </div>
        </div>
      )}
    </Layout>
  );
};

export default Listings;

// frontend_angular/src/app/pages/listings/listings.component.ts
// listings.component.ts
import { Component, OnInit } from '@angular/core';
import { ListingsService } from '../listings.service';

@Component({
  selector: 'app-listings',
  templateUrl: './listings.component.html',
  styleUrls: ['./listings.component.css']
})
export class ListingsComponent implements OnInit {
  listings: any[] = [];
  currentPage = 1;
  searchTerm = '';
  filterExchange = false;
  showRequestPopup = false;
  selectedListingUser: any = null;
  selectedBookId: any = null;

  constructor(private listingsService: ListingsService) { }

  ngOnInit(): void {
    this.fetchListings();
  }

  fetchListings(filterExchange: boolean = false): void {
    this.listingsService.getAllListings().subscribe(
      (response) => {
        if (filterExchange) {
          this.listings = response.filter(listing => listing.isExchange);
        } else {
          this.listings = response;
        }
      },
      (error) => {
        console.error('Error fetching listings:', error);
      }
    );
  }

  filterListings(): void {
    if (!this.searchTerm.trim()) {
      this.fetchListings();
    } else {
      this.listingsService.getAllListings().subscribe(
        (response) => {
          this.listings = response.filter(listing =>
            listing.title.toLowerCase().includes(this.searchTerm.toLowerCase())
          );
        },
        (error) => {
          console.error('Error fetching listings:', error);
        }
      );
    }
  }

  nextPage(): void {
    this.currentPage++;
  }

  prevPage(): void {
    if (this.currentPage > 1) {
      this.currentPage--;
    }
  }

  fetchUserDetails(userId: string): void {
    this.listingsService.fetchUserDetails(userId).subscribe(
      (userData) => {
        this.selectedListingUser = userData;
      },
      (error) => {
        console.error('Error fetching user details:', error);
      }
    );
  }

  handleExchangeClick(userId: string, bookId: string): void {
    this.fetchUserDetails(userId);
    this.selectedBookId = bookId;
    this.showRequestPopup = true;
  }

  handleRequestClick(): void {
    const token = localStorage.getItem('authToken');
    if (!token || !this.selectedListingUser || !this.selectedBookId) {
      return;
    }
  
    this.listingsService.sendExchangeRequest(this.selectedListingUser.email, this.selectedListingUser._id, this.selectedBookId, token).subscribe(
      () => {
        console.log('Exchange request sent successfully');
        window.alert('Exchange request sent successfully');
        this.showRequestPopup = false;
      },
      (error) => {
        console.error('Error sending exchange request:', error);
        window.alert('Error sending exchange request');
      }
    );
  }
}
<div class="container">
  <input 
      type="text" 
      class="form-control mb-3"
      style= "margin-top: 20px;"
      placeholder="Search by book name" 
      [(ngModel)]="searchTerm" 
      (input)="filterListings()"
  />
  <br><br>
  <label>
      <input 
          type="checkbox" 
          [(ngModel)]="filterExchange" 
          (change)="fetchListings(filterExchange)"
      />
      Show Exchange Listings
  </label>
  <br><br>
  <div class="card-container">
      <div class="card" *ngFor="let listing of listings">
          <img class="card-img-top" [src]="listing.img" alt="{{ listing.title }}">
          <div class="card-body">
              <h2 class="card-title">{{ listing.title }}</h2>
              <p class="card-text">Author: {{ listing.author }}</p>
              <p class="card-text">Price: {{ listing.inventory }}</p>
              <!-- Add more details here as needed -->
              <button class="btn btn-primary" (click)="handleExchangeClick(listing.userId , listing._id)" *ngIf="listing.isExchange; else buyButton">Exchange</button>
              <ng-template #buyButton>
                  <button class="btn btn-primary">Buy</button>
              </ng-template>
          </div>
      </div>
  </div>
</div>

<!-- Request Exchange Dialog -->
<div *ngIf="showRequestPopup" class="overlay">
    <div class="dialog">
      <h2>Request Exchange</h2>
      <p>Confirm your request to exchange with {{ selectedListingUser?.name }} for the book: {{ selectedBookId }}.</p>
      <button (click)="handleRequestClick()">Confirm</button>
      <button (click)="showRequestPopup = false">Cancel</button>
    </div>
  </div>
